### ISSUE TITLE
Реализация верная, но если оптимизировать, то вот так будет лучше

### ISSUE THREAD

**Issue by Ferguse** [erven1985/LoftSchool#3]
https://github.com/erven1985/LoftSchool/blob/ad0b4cb0ada6b89627c228eafca059b44994daf7/loftschool-example-hm1/src/index.js#L80

достаточно

`returnArgumentsArray() {
     return[...arguments]
}`

**Comment by erven1985** [comment]
Оптимизировал, так проще на самом деле.
